home:
    path: /
    controller: App\Controller\ReactController::home
index:
    path: index/{latitude}/{longitude}/{distance}
    controller: App\Controller\ReactController::index
    defaults:
        latitude: '54.898152'
        longitude: '23.904320'
        distance: '10'
modal:
    path: modal/{id}
    controller: App\Controller\ReactController::modal
search:
    path: search/{query}/{latitude}/{longitude}/{distance}
    controller: App\Controller\ReactController::search
    defaults:
        latitude: '54.898152'
        longitude: '23.904320'
        distance: '10'
similar_suggestions:
    path: similar
    controller: App\Controller\ReactController::similarSuggestions
    defaults:
        foodName: 'put past searches here'
different_suggestions:
    path: different
    controller: App\Controller\ReactController::differentSuggestions
    defaults:
        foodName: 'put past searches here'
favorite_restaurants:
    path: favorite
    controller: App\Controller\ReactController::favoriteRestaurants
    defaults:
        restaurantName: 'put past searches here'