home:
    path: /
    controller: App\Controller\ReactController::home
index:
    path: index/{latitude}/{longitude}/{distance}
    controller: App\Controller\ReactController::index
    defaults:
        latitude: '54.898152'
        longitude: '23.904320'
        distance: '10'
modal:
    path: modal/{id}
    controller: App\Controller\ReactController::modal
search:
    path: search/{query}/{latitude}/{longitude}/{distance}
    controller: App\Controller\ReactController::search
    defaults:
        latitude: '54.898152'
        longitude: '23.904320'
        distance: '10'
discover_something_new:
    path: different/{foodName}
    controller: App\Controller\ReactController::restaurantsToTry
    defaults:
        foodName: 'pasta,burger'
restaurants_you_may_like:
    path: favorite/{foodName}
    controller: App\Controller\ReactController::restaurantsYouMayLike
    defaults:
        foodName: 'pasta,burger'